[project]
name = "ur-simulation-playground"
version = "0.1.0"
authors = ["Mohamed Elobaid <mohamed.elobaid@kaust.edu.sa>"]
channels = ["https://prefix.dev/robostack-humble", "https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = "*"
compilers = "*"
cmake = ">=4.1.1,<5"
pkg-config = "*"
make = "*"
ninja = "*"


#ros
ros-humble-desktop = "*"
ros-humble-ur-description = ">=2.6.0,<3"
ros-humble-ur-robot-driver = ">=2.8.1,<3"
ros-humble-ros-gz-sim = ">=0.244.20,<0.245"
ros-humble-ur = ">=2.8.1,<3"
ros-humble-ur-msgs = ">=2.2.0,<3"
ros-humble-ur-moveit-config = ">=2.8.1,<3"
ros-humble-ur-dashboard-msgs = ">=2.8.1,<3"
ros-humble-ur-controllers = ">=2.8.1,<3"
ros-humble-ur-client-library = ">=2.1.0,<3"
ros-humble-joint-limits = ">=2.51.0,<3"
ros-humble-joint-state-broadcaster = ">=2.48.0,<3"
ros-humble-joint-state-publisher = ">=2.4.0,<3"
ros-humble-joint-state-publisher-gui = ">=2.4.0,<3"
ros-humble-joint-trajectory-controller = ">=2.48.0,<3"
ros-humble-ros2-control = ">=2.51.0,<3"
ros-humble-gz-ros2-control = "*"
ros-humble-ur-simulation-gz = "*"





[tasks]
launch-simulation = { cmd = "ros2 launch ur_simulation_gz ur_sim_control.launch.py initial_joint_controller:=scaled_joint_trajectory_controller", env = { IGN_GAZEBO_SYSTEM_PLUGIN_PATH = "$CONDA_PREFIX/lib", GZ_SIM_SYSTEM_PLUGIN_PATH = "$CONDA_PREFIX/lib" } }